[tox]
skipsdist = True
envlist = lint, py313

[testenv:lint]
deps = uv
skip_install = true
setenv =
    PYTHONPATH = {toxinidir}
commands_pre = uv sync --active --group dev --locked
commands =
    uv run --active ruff check .
    uv run --active ruff format --check .
    uv run --active mypy pstq

[testenv]
deps = uv
skip_install = true
setenv =
    PYTHONPATH = {toxinidir}
commands_pre = uv sync --active --group dev --locked
commands =
    uv run --active pytest --cov=pstq tests/
